# Generated by Django 5.2.8 on 2026-07-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('examName', models.CharField(max_length=150)),
                ('examTopic', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('passingMarks', models.PositiveIntegerField(default=60)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('description', models.TextField()),
                ('instruction', models.TextField()),
            ],
        ),
    ]
